[package]
name = "capped_collections"
version = "0.2.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Collections with compile-time set capacities."
repository = "https://github.com/coruscateor/capped_collections"
homepage = "https://coruscateor.com/projects/capped_collections"
keywords = ["capped", "vec", "map", "array", "set"]
categories = ["data-structures", "no-std"]
authors = ["Paul Saunders"]

[dependencies]

serde = { version = "1.0.228", optional = true }

inc_dec = "0.1.0"

delegate = "0.13.5"

accessorise = "0.2.0"

[features]
no_std = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
